services:
  postgres:
    image: postgres:16
    container_name: edunexus-postgres
    environment:
      POSTGRES_DB: edunexus
      POSTGRES_USER: edunexus
      POSTGRES_PASSWORD: edunexus
    ports: ["5433:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edunexus"]
      interval: 5s
      retries: 10
  redis:
    image: redis:7
    container_name: edunexus-redis
    ports: ["6380:6379"]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: edunexus-rabbitmq
    ports: ["5673:5672", "15673:15672"]
  minio:
    image: minio/minio
    container_name: edunexus-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ["9002:9000", "9003:9001"]
    volumes: [miniodata:/data]
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: edunexus-opensearch
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports: ["9201:9200"]
    volumes: [osdata:/usr/share/opensearch/data]
volumes:
  pgdata: {}
  miniodata: {}
  osdata: {}
