namespace EduNexus.Api;

public sealed record CreateTenantReq(string Slug, string Name);
public sealed record CreateOrgReq(Guid TenantId, string Code, string Name);
public sealed record CreateUnitReq(Guid TenantId, string Code, string Name, Guid? ParentId = null, Guid? LeaderPersonId = null, Guid? DeputyPersonId = null);
public sealed record CreatePersonReq(Guid TenantId, string Type, string FullName, string? Email, Guid? DepartmentId = null, string? AcademicRank = null);
public sealed record AddRecordCommentReq(Guid TenantId, string EntityType, Guid EntityId, Guid AuthorId, string Content, bool IsInternalOnly);
public sealed record FollowEntityReq(Guid TenantId, string EntityType, Guid EntityId, Guid PersonId);
public sealed record CreateActivityReq(Guid TenantId, string EntityType, Guid EntityId, string Type, Guid AssigneeId, string Summary, DateTimeOffset DueDate);
public sealed record CompleteActivityReq(Guid TenantId);
public sealed record CreateWorkspaceReq(Guid TenantId, string Code, string Name, string? Description);
public sealed record AddDocumentTagReq(Guid TenantId, string Category, string Value);
public sealed record DevTokenReq(string Subject, Guid TenantId, string[]? Permissions, Guid? PersonId = null);
public sealed record CreateRoleReq(Guid TenantId, string Code, string Name, string[]? Permissions);
public sealed record AssignRoleReq(Guid TenantId, Guid PersonId, string RoleCode, string? Scope, DateTimeOffset? ExpiresAt);
public sealed record RevokeRoleReq(Guid TenantId, Guid PersonId, string RoleCode);
public sealed record RecipientReq(string? PersonId, string DisplayName, bool IsExternal);
public sealed record CreateCorrespondenceReq(Guid TenantId, string Type, string Subject, string Content, Guid AuthorId, string? Priority, bool IsConfidential, RecipientReq[]? Recipients, Guid? ParentCorrespondenceId = null);
public sealed record CreateRoutingSlipReq(Guid TenantId, Guid FromPersonId, Guid? ToUnitId, Guid? ToPersonId, string ActionRequired, string Instructions, DateTimeOffset? DueAt);
public sealed record CastMeetingVoteReq(Guid TenantId, Guid AgendaItemId, Guid PersonId, string Choice, string? Remarks = null);
public sealed record SetDocumentRetentionReq(Guid TenantId, string Standard, int RetentionPeriodMonths, string DispositionAction, int ReviewIntervalMonths, Guid? ReviewedByPersonId = null, string? Notes = null);
public sealed record SubmitCorrespondenceReq(Guid TenantId, Guid ReviewerId);
public sealed record DecideApprovalReq(Guid TenantId, Guid? DecidedBy, bool Approve, string? Comment);
public sealed record RequestChangesReq(Guid TenantId, Guid DecidedBy, string? Comment);
public sealed record DelegateApprovalReq(Guid TenantId, Guid DelegatedBy, Guid DelegateTo);
public sealed record CompleteTaskReq(Guid TenantId);
public sealed record UpdateTaskReq(Guid TenantId, string? Title, string? Description, string? Priority, int? Progress, string? Status);
public sealed record AddTaskEvidenceReq(Guid TenantId, Guid UploadedBy, string ObjectKey, string FileName);
public sealed record AddTaskCommentReq(Guid TenantId, Guid AuthorId, string Text);
public sealed record CreateCommitteeReq(Guid TenantId, string Code, string Name);
public sealed record AddMemberReq(Guid TenantId, Guid PersonId, string? Role);
public sealed record AgendaReq(string Title, string? Description);
public sealed record CreateMeetingReq(Guid TenantId, Guid CommitteeId, string Title, DateTimeOffset StartsAt, AgendaReq[]? Agenda);
public sealed record RecordAttendanceReq(Guid TenantId, Guid PersonId, string Status);
public sealed record ConcludeMeetingReq(Guid TenantId, string? Minutes);
public sealed record CreateDecisionReq(Guid TenantId, string Text);
public sealed record CreateDecisionActionReq(Guid TenantId, Guid AssigneeId, string Description, DateTimeOffset? DueAt);
public sealed record AdvanceActionReq(Guid TenantId, string Status);
public sealed record CreatePolicyReq(Guid TenantId, string Code, string Title, string? Content);
public sealed record PublishPolicyReq(Guid TenantId);
public sealed record AcknowledgePolicyReq(Guid TenantId, Guid PersonId);
public sealed record CreateDocumentReq(Guid TenantId, string Title);
public sealed record UploadUrlReq(Guid TenantId, string FileName);
public sealed record AddVersionReq(Guid TenantId, string ObjectKey, long SizeBytes, string? Sha256, bool Publish);
public sealed record CreateStandardReq(Guid TenantId, string Code, string Title);
public sealed record CreateCriterionReq(Guid TenantId, Guid StandardId, string Code, string Text);
public sealed record AddEvidenceReq(Guid TenantId, Guid CriterionId, string EntityType, Guid EntityId, string? Note);
public sealed record CreateFindingReq(Guid TenantId, Guid CriterionId, string Severity, string Text);
public sealed record CreateCorrectiveActionReq(Guid TenantId, Guid FindingId, Guid AssigneeId, string Description, DateTimeOffset? DueAt);
public sealed record CreatePlanReq(Guid TenantId, string Title, int YearFrom, int YearTo);
public sealed record CreateObjectiveReq(Guid TenantId, Guid PlanId, string Code, string Text);
public sealed record CreateKpiReq(Guid TenantId, Guid ObjectiveId, string Name, double Target, double Current, string? Unit);
public sealed record KpiReadingReq(Guid TenantId, double Current);
public sealed record AskReq(Guid TenantId, string Question, string? Capability);
public sealed record ShareDocumentReq(Guid TenantId, Guid PersonId, DateTimeOffset? ExpiresAt);
public sealed record UpdateDocumentReq(Guid TenantId, string? Title, string? Classification, DateTimeOffset? RetainUntil, string? Status);
public sealed record RegisterEndpointReq(Guid TenantId, string EventType, string TargetUrl, string? Secret);
public sealed record CreateFormReq(Guid TenantId, string Code, string Name, string Category, string SchemaJson);
public sealed record ValidateSubmissionReq(Guid TenantId, string DataJson);
public sealed record CreateRequestReq(Guid TenantId, string Category, string Title, Guid SubmitterId, Guid? FormId, string? DataJson);
public sealed record SubmitRequestReq(Guid TenantId, Guid? ReviewerId, string? WorkflowCode);
public sealed record CreateWorkflowReq(Guid TenantId, string Code, string Name, string NodesJson);
public sealed record CreateCommunicationReq(Guid TenantId, string Kind, string Title, string? Body, Guid AuthorId, bool RequiresAction, DateTimeOffset? DueAt, Guid[]? TargetPersonIds);
public sealed record PublishCommunicationReq(Guid TenantId);
public sealed record CreateTemplateReq(Guid TenantId, string Code, string Channel, string? Subject, string BodyTemplate);
public sealed record CreateAuthorityDelegationReq(Guid TenantId, Guid FromPersonId, Guid ToPersonId, string Scope, DateTimeOffset ExpiresAt);
public sealed record CreateDocActionRuleReq(Guid TenantId, string TriggerCategory, string TriggerValue, string ActionType, string? TargetValue = null);
