global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/alerts.yml
scrape_configs:
  - job_name: edunexus-api
    static_configs:
      - targets: ['host.docker.internal:5299']
    metrics_path: /metrics
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
